/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BackendsRouteImport } from './routes/backends'
import { Route as LabRouteImport } from './routes/lab'
import { Route as AuthenticatedCircuitsRouteImport } from './routes/_authenticated/circuits'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInstructorRouteImport } from './routes/_authenticated/instructor'
import { Route as CIdRouteImport } from './routes/c.$id'
import { Route as ChallengesIndexRouteImport } from './routes/challenges.index'
import { Route as ChallengesChallengeIdRouteImport } from './routes/challenges.$challengeId'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnLessonIdRouteImport } from './routes/learn.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendsRoute = BackendsRouteImport.update({
  id: '/backends',
  path: '/backends',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCircuitsRoute = AuthenticatedCircuitsRouteImport.update({
  id: '/circuits',
  path: '/circuits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInstructorRoute = AuthenticatedInstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CIdRoute = CIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIndexRoute = ChallengesIndexRouteImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesChallengeIdRoute = ChallengesChallengeIdRouteImport.update({
  id: '/challenges/$challengeId',
  path: '/challenges/$challengeId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnLessonIdRoute = LearnLessonIdRouteImport.update({
  id: '/learn/$lessonId',
  path: '/learn/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/backends': typeof BackendsRoute
  '/lab': typeof LabRoute
  '/circuits': typeof AuthenticatedCircuitsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/instructor': typeof AuthenticatedInstructorRoute
  '/c/$id': typeof CIdRoute
  '/challenges/$challengeId': typeof ChallengesChallengeIdRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/challenges/': typeof ChallengesIndexRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/backends': typeof BackendsRoute
  '/lab': typeof LabRoute
  '/circuits': typeof AuthenticatedCircuitsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/instructor': typeof AuthenticatedInstructorRoute
  '/c/$id': typeof CIdRoute
  '/challenges/$challengeId': typeof ChallengesChallengeIdRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/challenges': typeof ChallengesIndexRoute
  '/learn': typeof LearnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/backends': typeof BackendsRoute
  '/lab': typeof LabRoute
  '/_authenticated/circuits': typeof AuthenticatedCircuitsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/instructor': typeof AuthenticatedInstructorRoute
  '/c/$id': typeof CIdRoute
  '/challenges/$challengeId': typeof ChallengesChallengeIdRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/challenges/': typeof ChallengesIndexRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/backends'
    | '/lab'
    | '/circuits'
    | '/dashboard'
    | '/instructor'
    | '/c/$id'
    | '/challenges/$challengeId'
    | '/learn/$lessonId'
    | '/challenges/'
    | '/learn/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/backends'
    | '/lab'
    | '/circuits'
    | '/dashboard'
    | '/instructor'
    | '/c/$id'
    | '/challenges/$challengeId'
    | '/learn/$lessonId'
    | '/challenges'
    | '/learn'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/backends'
    | '/lab'
    | '/_authenticated/circuits'
    | '/_authenticated/dashboard'
    | '/_authenticated/instructor'
    | '/c/$id'
    | '/challenges/$challengeId'
    | '/learn/$lessonId'
    | '/challenges/'
    | '/learn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BackendsRoute: typeof BackendsRoute
  LabRoute: typeof LabRoute
  CIdRoute: typeof CIdRoute
  ChallengesChallengeIdRoute: typeof ChallengesChallengeIdRoute
  LearnLessonIdRoute: typeof LearnLessonIdRoute
  ChallengesIndexRoute: typeof ChallengesIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backends': {
      id: '/backends'
      path: '/backends'
      fullPath: '/backends'
      preLoaderRoute: typeof BackendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/circuits': {
      id: '/_authenticated/circuits'
      path: '/circuits'
      fullPath: '/circuits'
      preLoaderRoute: typeof AuthenticatedCircuitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instructor': {
      id: '/_authenticated/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof AuthenticatedInstructorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/c/$id': {
      id: '/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof CIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/': {
      id: '/challenges/'
      path: '/challenges'
      fullPath: '/challenges/'
      preLoaderRoute: typeof ChallengesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/$challengeId': {
      id: '/challenges/$challengeId'
      path: '/challenges/$challengeId'
      fullPath: '/challenges/$challengeId'
      preLoaderRoute: typeof ChallengesChallengeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$lessonId': {
      id: '/learn/$lessonId'
      path: '/learn/$lessonId'
      fullPath: '/learn/$lessonId'
      preLoaderRoute: typeof LearnLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCircuitsRoute: typeof AuthenticatedCircuitsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInstructorRoute: typeof AuthenticatedInstructorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCircuitsRoute: AuthenticatedCircuitsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInstructorRoute: AuthenticatedInstructorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BackendsRoute: BackendsRoute,
  LabRoute: LabRoute,
  CIdRoute: CIdRoute,
  ChallengesChallengeIdRoute: ChallengesChallengeIdRoute,
  LearnLessonIdRoute: LearnLessonIdRoute,
  ChallengesIndexRoute: ChallengesIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
